---
title: "UFC"
author: "Sarnath Chari"
date: "4/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


#Importing and Cleaning Data

```{r}
ufc_data <- read.csv("preprocessed_data.csv")

str(ufc_data)
head(ufc_data)

summary(ufc_data)
head(ufc_data)
ufc_data$B_draw <- NULL
ufc_data$R_draw <- NULL
ufc_data$B_current_lose_streak <- NULL
ufc_data$B_current_win_streak <- NULL
ufc_data$R_current_lose_streak <- NULL
ufc_data$R_current_win_streak <- NULL
ufc_data$B_longest_win_streak <- NULL
ufc_data$R_longest_win_streak <- NULL
ufc_data$B_wins <- NULL
ufc_data$R_wins <- NULL
ufc_data$B_losses <- NULL
ufc_data$R_losses <- NULL

ufc_data$B_win_by_Decision_Majority <- NULL
ufc_data$B_win_by_Decision_Split <- NULL
ufc_data$B_win_by_Decision_Unanimous <- NULL
ufc_data$B_win_by_KO.TKO <- NULL
ufc_data$B_win_by_Submission <- NULL
ufc_data$B_win_by_TKO_Doctor_Stoppage <- NULL

ufc_data$R_win_by_Decision_Majority <- NULL
ufc_data$R_win_by_Decision_Split <- NULL
ufc_data$R_win_by_Decision_Unanimous <- NULL
ufc_data$R_win_by_KO.TKO <- NULL
ufc_data$R_win_by_Submission <- NULL
ufc_data$R_win_by_TKO_Doctor_Stoppage <- NULL

any(is.na(ufc_data))
ufc_data$Winner <- ifelse(ufc_data$Winner == "Blue", 1, 0)
ufc_data$Winner = as.factor(ufc_data$Winner)
any(is.na(ufc_data))
ufc_data$DeltaHeight = ufc_data$B_Height_cms - ufc_data$R_Height_cms
ufc_data$B_Height_cms <- NULL
ufc_data$R_Height_cms <- NULL
any(is.na(ufc_data))

ufc_data$DeltaReach = ufc_data$B_Reach_cms - ufc_data$R_Reach_cms
any(is.na(ufc_data))
ufc_data$B_Reach_cms <- NULL
ufc_data$R_Reach_cms <- NULL

ufc_data$DeltaWeight = ufc_data$B_Weight_lbs - ufc_data$R_Weight_lbs
ufc_data$B_Weight_lbs <- NULL
ufc_data$R_Weight_lbs <- NULL

ufc_data$B_avg_BODY_Prop = ifelse(ufc_data$B_avg_BODY_att== 0 , 0 , ufc_data$B_avg_BODY_landed/ufc_data$B_avg_BODY_att)
ufc_data$B_avg_BODY_landed <- NULL
ufc_data$B_avg_BODY_att <- NULL
any(is.na(ufc_data))

ufc_data$B_avg_CLINCH_Prop = ifelse(ufc_data$B_avg_CLINCH_att== 0 , 0 , ufc_data$B_avg_CLINCH_landed/ufc_data$B_avg_CLINCH_att)
ufc_data$B_avg_CLINCH_landed <- NULL
ufc_data$B_avg_CLINCH_att <- NULL

ufc_data$B_avg_DISTANCE_Prop = ifelse(ufc_data$B_avg_DISTANCE_att== 0 , 0 , ufc_data$B_avg_DISTANCE_landed/ufc_data$B_avg_DISTANCE_att)
ufc_data$B_avg_DISTANCE_landed <- NULL
ufc_data$B_avg_DISTANCE_att <- NULL

ufc_data$B_avg_GROUND_Prop = ifelse(ufc_data$B_avg_GROUND_att== 0 , 0 , ufc_data$B_avg_GROUND_landed/ufc_data$B_avg_GROUND_att)
ufc_data$B_avg_GROUND_landed <- NULL
ufc_data$B_avg_GROUND_att <- NULL

ufc_data$B_avg_HEAD_Prop = ifelse(ufc_data$B_avg_HEAD_att== 0 , 0 , ufc_data$B_avg_HEAD_landed/ufc_data$B_avg_HEAD_att)
ufc_data$B_avg_HEAD_att <- NULL
ufc_data$B_avg_HEAD_landed <- NULL

ufc_data$B_avg_LEG_Prop = ifelse(ufc_data$B_avg_LEG_att== 0 , 0 , ufc_data$B_avg_LEG_landed/ufc_data$B_avg_LEG_att)
ufc_data$B_avg_LEG_landed <- NULL
ufc_data$B_avg_LEG_att <- NULL

ufc_data$B_avg_TOTAL_STR_Prop = ifelse(ufc_data$B_avg_TOTAL_STR_att== 0 , 0 , ufc_data$B_avg_TOTAL_STR_landed/ufc_data$B_avg_TOTAL_STR_att)
ufc_data$B_avg_TOTAL_STR_landed <- NULL
ufc_data$B_avg_TOTAL_STR_att <- NULL

ufc_data$B_avg_opp_BODY_landed <- NULL 
ufc_data$B_avg_opp_BODY_att <- NULL

ufc_data$B_avg_opp_CLINCH_landed <- NULL
ufc_data$B_avg_opp_CLINCH_att <- NULL

ufc_data$B_avg_opp_DISTANCE_landed <- NULL
ufc_data$B_avg_opp_DISTANCE_att <- NULL

ufc_data$B_avg_opp_GROUND_landed <- NULL
ufc_data$B_avg_opp_GROUND_att <- NULL

ufc_data$B_avg_opp_HEAD_landed <- NULL
ufc_data$B_avg_opp_HEAD_att <- NULL

ufc_data$B_avg_opp_LEG_landed <- NULL
ufc_data$B_avg_opp_LEG_att <- NULL

ufc_data$B_avg_opp_TOTAL_STR_landed <- NULL
ufc_data$B_avg_opp_TOTAL_STR_att <- NULL


ufc_data$R_avg_BODY_Prop = ifelse(ufc_data$R_avg_BODY_att== 0 , 0 , ufc_data$R_avg_BODY_landed/ufc_data$R_avg_BODY_att)
ufc_data$R_avg_BODY_landed <- NULL
ufc_data$R_avg_BODY_att <- NULL

ufc_data$R_avg_CLINCH_Prop = ifelse(ufc_data$R_avg_CLINCH_att== 0 , 0 , ufc_data$R_avg_CLINCH_landed/ufc_data$R_avg_CLINCH_att)
ufc_data$R_avg_CLINCH_landed <- NULL
ufc_data$R_avg_CLINCH_att <- NULL

ufc_data$R_avg_DISTANCE_Prop = ifelse(ufc_data$R_avg_DISTANCE_landed== 0 , 0 , ufc_data$R_avg_DISTANCE_att/ufc_data$R_avg_DISTANCE_landed)
ufc_data$R_avg_DISTANCE_att <- NULL
ufc_data$R_avg_DISTANCE_landed <- NULL

ufc_data$R_avg_GROUND_Prop = ifelse(ufc_data$R_avg_GROUND_att== 0 , 0 , ufc_data$R_avg_GROUND_landed/ufc_data$R_avg_GROUND_att)
ufc_data$R_avg_GROUND_landed <- NULL
ufc_data$R_avg_GROUND_att <- NULL

ufc_data$R_avg_HEAD_Prop = ifelse(ufc_data$R_avg_HEAD_att== 0 , 0 , ufc_data$R_avg_HEAD_landed/ufc_data$R_avg_HEAD_att)
ufc_data$R_avg_HEAD_landed <- NULL 
ufc_data$R_avg_HEAD_att <- NULL

ufc_data$R_avg_LEG_Prop = ifelse(ufc_data$R_avg_LEG_att== 0 , 0 , ufc_data$R_avg_LEG_landed/ufc_data$R_avg_LEG_att)
ufc_data$R_avg_LEG_landed <- NULL
ufc_data$R_avg_LEG_att <- NULL

ufc_data$R_avg_TOTAL_STR_Prop = ifelse(ufc_data$R_avg_TOTAL_STR_att== 0 , 0 , ufc_data$R_avg_TOTAL_STR_landed / ufc_data$R_avg_TOTAL_STR_att)
ufc_data$R_avg_TOTAL_STR_landed <- NULL
ufc_data$R_avg_TOTAL_STR_att <- NULL

ufc_data$R_avg_opp_BODY_landed <- NULL
ufc_data$B_avg_opp_BODY_att <- NULL

ufc_data$R_avg_opp_CLINCH_landed <- NULL
ufc_data$R_avg_opp_CLINCH_att <- NULL

ufc_data$R_avg_opp_DISTANCE_landed <- NULL
ufc_data$R_avg_opp_DISTANCE_att <- NULL

ufc_data$R_avg_opp_GROUND_landed <- NULL
ufc_data$R_avg_opp_GROUND_att <- NULL

ufc_data$R_avg_opp_HEAD_landed <- NULL
ufc_data$R_avg_opp_HEAD_att <- NULL

ufc_data$R_avg_opp_LEG_landed <- NULL
ufc_data$R_avg_opp_LEG_att <- NULL

ufc_data$R_avg_opp_TOTAL_STR_landed <- NULL
ufc_data$R_avg_opp_TOTAL_STR_att <- NULL


ufc_data$Delta_BODY_Prop = ufc_data$B_avg_BODY_Prop - ufc_data$R_avg_BODY_Prop
ufc_data$B_avg_BODY_Prop <- NULL
ufc_data$R_avg_BODY_Prop <- NULL

ufc_data$Delta_CLINCH_Prop = ufc_data$B_avg_CLINCH_Prop - ufc_data$R_avg_CLINCH_Prop
ufc_data$B_avg_CLINCH_Prop<- NULL
ufc_data$R_avg_CLINCH_Prop <- NULL

ufc_data$Delta_DISTANCE_Prop = ufc_data$B_avg_DISTANCE_Prop - ufc_data$R_avg_DISTANCE_Prop
ufc_data$B_avg_DISTANCE_Prop <- NULL
ufc_data$R_avg_DISTANCE_Prop <- NULL

ufc_data$Delta_GROUND_Prop = ufc_data$B_avg_GROUND_Prop - ufc_data$R_avg_GROUND_Prop
ufc_data$B_avg_GROUND_Prop <- NULL
ufc_data$R_avg_GROUND_Prop<- NULL

ufc_data$Delta_HEAD_Prop = ufc_data$B_avg_HEAD_Prop - ufc_data$R_avg_HEAD_Prop
ufc_data$B_avg_HEAD_Prop <- NULL
ufc_data$R_avg_HEAD_Prop <- NULL

ufc_data$Delta_LEG_Prop = ufc_data$B_avg_LEG_Prop - ufc_data$R_avg_LEG_Prop
ufc_data$B_avg_LEG_Prop <- NULL
ufc_data$R_avg_LEG_Prop <- NULL

ufc_data$Delta_TOTAL_STR_Prop = ufc_data$B_avg_TOTAL_STR_Prop - ufc_data$R_avg_TOTAL_STR_Prop
ufc_data$B_avg_TOTAL_STR_Prop <- NULL
ufc_data$R_avg_TOTAL_STR_Prop <- NULL

ufc_data$B_avg_opp_PASS <- NULL                   
ufc_data$B_avg_opp_REV         <- NULL            
ufc_data$B_avg_opp_SIG_STR_att        <- NULL     
ufc_data$B_avg_opp_SIG_STR_landed   <- NULL      
ufc_data$B_avg_opp_SIG_STR_pct <- NULL
ufc_data$B_avg_opp_SUB_ATT  <- NULL               
ufc_data$B_avg_opp_TD_att <- NULL                 
ufc_data$B_avg_opp_TD_landed  <- NULL             
ufc_data$B_avg_opp_TD_pct   <- NULL   
ufc_data$B_avg_opp_KD   <- NULL   

ufc_data$R_avg_opp_BODY_att   <- NULL                 
ufc_data$R_avg_opp_KD        <- NULL               
ufc_data$R_avg_opp_PASS      <- NULL               
ufc_data$R_avg_opp_REV       <- NULL               
ufc_data$R_avg_opp_SIG_STR_att   <- NULL           
ufc_data$R_avg_opp_SIG_STR_landed  <- NULL         
ufc_data$R_avg_opp_SIG_STR_pct     <- NULL         
ufc_data$R_avg_opp_SUB_ATT         <- NULL         
ufc_data$R_avg_opp_TD_att            <- NULL       
ufc_data$R_avg_opp_TD_landed         <- NULL       
ufc_data$R_avg_opp_TD_pct      <- NULL



# Looking specifically at bantamWeightMen

#winner <- glm(Winner ~ bantamWeightMen$Delta_BODY_Prop + bantamWeightMen$Delta_CLINCH_Prop + bantamWeightMen$Delta_DISTANCE_Prop + bantamWeightMen$Delta_GROUND_Prop + bantamWeightMen$Delta_HEAD_Prop + bantamWeightMen$Delta_LEG_Prop + bantamWeightMen$Delta_TOTAL_STR_Prop, data = bantamWeightMen, family = binomial)

#summary(winner)

#winnerc <- glm(Winner ~ catchWeightMen$Delta_BODY_Prop + catchWeightMen$Delta_CLINCH_Prop + catchWeightMen$Delta_DISTANCE_Prop + catchWeightMen$Delta_GROUND_Prop + catchWeightMen$Delta_HEAD_Prop + catchWeightMen$Delta_LEG_Prop + catchWeightMen$Delta_TOTAL_STR_Prop, data = catchWeightMen, family = binomial)

#summary(winnerc)

  #Remove everything but deletas
str(ufc_data)

ufc_data$B_draw                            = NULL
ufc_data$B_avg_KD                          = NULL
ufc_data$B_avg_PASS                        = NULL
ufc_data$B_avg_REV                         = NULL
ufc_data$B_avg_SIG_STR_att                 = NULL
ufc_data$B_avg_SIG_STR_landed              = NULL 
ufc_data$B_avg_SIG_STR_pct                 = NULL 
ufc_data$B_avg_SUB_ATT                     = NULL
ufc_data$B_avg_TD_att                      = NULL
ufc_data$B_avg_TD_landed                   = NULL
ufc_data$B_avg_TD_pct                      = NULL
ufc_data$B_total_rounds_fought             = NULL 
ufc_data$B_total_time_fought.seconds.      = NULL
ufc_data$B_total_title_bouts               = NULL
ufc_data$R_avg_KD                          = NULL
ufc_data$R_avg_PASS                        = NULL
ufc_data$R_avg_REV                         = NULL
ufc_data$R_avg_SIG_STR_att                 = NULL
ufc_data$R_avg_SIG_STR_landed              = NULL
ufc_data$R_avg_SIG_STR_pct                 = NULL
ufc_data$R_avg_SUB_ATT                     = NULL
ufc_data$R_avg_TD_att                      = NULL
ufc_data$R_avg_TD_landed                   = NULL
ufc_data$R_avg_TD_pct                      = NULL
ufc_data$R_total_rounds_fought             = NULL
ufc_data$R_total_time_fought.seconds.      = NULL
ufc_data$R_total_title_bouts               = NULL
ufc_data$B_age                             = NULL
ufc_data$R_age                             = NULL
ufc_data$B_Stance_Open.Stance              = NULL
ufc_data$B_Stance_Orthodox                 = NULL
ufc_data$B_Stance_Sideways                 = NULL
ufc_data$B_Stance_Southpaw                 = NULL 
ufc_data$B_Stance_Switch                   = NULL 
ufc_data$R_Stance_Open.Stance              = NULL 
ufc_data$R_Stance_Orthodox                 = NULL 
ufc_data$R_Stance_Southpaw                 = NULL 
ufc_data$R_Stance_Switch                   = NULL

bantamWeightMen = ufc_data[ufc_data$weight_class_Bantamweight==1,]
catchWeightMen = ufc_data[ufc_data$weight_class_Catch.Weight==1,]
featherWeightMen = ufc_data[ufc_data$weight_class_Featherweight==1,]
flyWeightMen = ufc_data[ufc_data$weight_class_Flyweight==1,]
heavyWeightMen = ufc_data[ufc_data$weight_class_Heavyweight==1,]
lightHeavyWeightMen = ufc_data[ufc_data$weight_class_Light.Heavyweight==1,]
lightWeightMen = ufc_data[ufc_data$weight_class_Lightweight==1,]
middleWeightMen = ufc_data[ufc_data$weight_class_Middleweight==1,]
openWeightMen = ufc_data[ufc_data$weight_class_Open.Weight==1,]
welterWeightMen = ufc_data[ufc_data$weight_class_Welterweight==1,]
bantamWeightWomen = ufc_data[ufc_data$weight_class_Women.s.Bantamweight==1,]
featherWeightWomen = ufc_data[ufc_data$weight_class_Women.s.Featherweight==1,]
flyWeightWomen = ufc_data[ufc_data$weight_class_Women.s.Flyweight==1,]
strawWeightWomen = ufc_data[ufc_data$weight_class_Women.s.Strawweight==1,]

set.seed(65)
randomData <- lightWeightMen[sample(nrow(lightWeightMen)), ]
any(is.na(randomData))
#2800
dataTrain <- randomData[1:560, -1]
dataTest <- randomData[561:703, -1]
dataTrainLabels = randomData[1:560, 1]
dataTestLabels = randomData[561:703, 1]

dataTestLabelsWords = data.frame(dataTestLabels)
dataTrainLabelsWords = data.frame(dataTrainLabels)

dataTrainWithLabels = dataTrain
dataTestWithLabels = dataTest

dataTrainWithLabels$Label <- ifelse(dataTrainLabelsWords == 0, "no", "yes")
dataTestWithLabels$Label <- ifelse(dataTestLabelsWords == 0, "no", "yes")

dataTrainWithLabels$Label = as.factor(dataTrainWithLabels$Label)
dataTestWithLabels$Label = as.factor(dataTestWithLabels$Label)

library(gmodels)
library(C50)
error_cost <- matrix(c(0, 0, 0, 0), nrow = 2)

# apply the cost matrix to the tree
#decisionTree2 <- C5.0(dataTrain[1:64], dataTrainWithLabels$Label, trials = 1000,
 #                         costs = error_cost)
decisionTree2 <- C5.0(dataTrain[1:26], dataTrainWithLabels$Label, trials = 100, costs=error_cost)
treePredictions <- predict(decisionTree2, dataTest[1:26])
CrossTable(dataTestWithLabels$Label, treePredictions,
           prop.chisq = FALSE, prop.c = FALSE, prop.r = FALSE,
           dnn = c('Actual Win', 'Predicted Win'))

summary(decisionTree2)

set.seed(65)
randomData <- strawWeightWomen[sample(nrow(strawWeightWomen)), ]

str(randomData)
any(is.na(randomData))
#2800
dataTrain <- randomData[1:75, -1]
dataTest <- randomData[76:98, -1]
dataTrainLabels = randomData[1:75, 1]
dataTestLabels = randomData[76:98, 1]



dataTestLabelsWords = data.frame(dataTestLabels)
dataTrainLabelsWords = data.frame(dataTrainLabels)

str(dataTestLabelsWords)
dataTrainWithLabels = dataTrain
dataTestWithLabels = dataTest

dataTrainWithLabels$Label <- ifelse(dataTrainLabelsWords == 0, "no", "yes")
dataTestWithLabels$Label <- ifelse(dataTestLabelsWords == 0, "no", "yes")

dataTrainWithLabels$Label = as.factor(dataTrainWithLabels$Label)
dataTestWithLabels$Label = as.factor(dataTestWithLabels$Label)

library(gmodels)
library(C50)
error_cost <- matrix(c(0, 0, 0, 0), nrow = 2)

# apply the cost matrix to the tree
#decisionTree2 <- C5.0(dataTrain[1:64], dataTrainWithLabels$Label, trials = 1000,
 #                         costs = error_cost)
decisionTree2 <- C5.0(dataTrain[1:26], dataTrainWithLabels$Label, trials = 100, costs=error_cost)
treePredictions <- predict(decisionTree2, dataTest[1:26])
CrossTable(dataTestWithLabels$Label, treePredictions,
           prop.chisq = FALSE, prop.c = FALSE, prop.r = FALSE,
           dnn = c('Actual Win', 'Predicted Win'))

```

